name: Terraform

on:
   pull_request:
     branches: [ master ]

env:
  TF_IN_AUTOMATION: true

jobs:
  terraform:
    name: Run Terraform Fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -diff -recursive
